root: ./

redirects:
  mews-operations/operations: mews-operations/README.md
  channel-manager-operations/operations: channel-manager-operations/README.md
  mews-operations/operations/reservations: mews-operations/reservations.md
  mews-operations/operations/inventory: mews-operations/inventory.md
  mews-operations/operations/configuration: mews-operations/configuration.md
  certification: your-journey/certification.md
  channels: use-cases/channels.md
  channel-manager-operations/operations/inventory: channel-manager-operations/inventory.md
  channel-manager-api: channel-manager-operations/README.md
